"""change Event_category_id to lower case in Event_categories

Revision ID: 1e28d8397ec3
Revises: 0eaf77c5d5ed
Create Date: 2025-02-21 22:10:56.156810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e28d8397ec3'
down_revision = '0eaf77c5d5ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Event_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_category_id', sa.Integer(), nullable=False))
        batch_op.drop_column('Event_category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Event_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Event_category_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('event_category_id')

    # ### end Alembic commands ###
