"""Apagando tabelas duplicadas

Revision ID: 455788657ea0
Revises: e2da19423aae
Create Date: 2025-02-24 20:23:39.682642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '455788657ea0'
down_revision = 'e2da19423aae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_categories', schema=None) as batch_op:
        batch_op.drop_constraint('event_categories_event_category_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_categories', schema=None) as batch_op:
        batch_op.create_unique_constraint('event_categories_event_category_id_key', ['event_category_id'])

    # ### end Alembic commands ###
