"""change field event_category id to nullable = true

Revision ID: 522e7b88389f
Revises: 
Create Date: 2025-02-28 10:41:14.937670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522e7b88389f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('event_category_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('event_category_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
