"""testando bug

Revision ID: 551dc9bf1805
Revises: 1e28d8397ec3
Create Date: 2025-02-23 01:52:00.145759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '551dc9bf1805'
down_revision = '1e28d8397ec3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Event_categories', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['event_category_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Event_categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
