"""Change field available_quantity to total_available_quantity in table tickets

Revision ID: 8ca2840209e3
Revises: 4b8a920e5804
Create Date: 2025-02-25 02:32:59.866998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ca2840209e3'
down_revision = '4b8a920e5804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_available_quantity', sa.Integer(), nullable=False))
        batch_op.drop_column('available_quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_quantity', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('total_available_quantity')

    # ### end Alembic commands ###
